# Generated by Django 4.2.3 on 2023-07-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='age',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='current_estimate_emp',
        ),
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedIn_url',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='locality',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='size_range',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='total_estimate_emp',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='year_founded',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
